// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/generate_types.py
// Source: robot/geometry/types.py

// Generated using python-to-typescript-interfaces.
// See https://github.com/NalyzeSolutions/python_to_typescript_interfaces

export interface GlobalCoordinate {
  x: number
  y: number
}

export interface LocalCoordinate {
  x: number
  y: number
}

export interface LocalPose {
  position: LocalCoordinate
  heading: number
}

export interface GlobalPose {
  position: GlobalCoordinate
  heading: number
}

export interface UltrasonicSensor {
  pose: LocalPose
  name: string
}
