#!/usr/bin/env python3
"""
Generate TypeScript interfaces from Python dataclasses.

This script uses python-to-typescript-interfaces to convert our geometry
dataclasses into TypeScript interfaces for use in the React frontend.

Output: frontend/src/types/generated.ts

Usage:
    python scripts/generate_types.py
"""

import subprocess
import sys
from pathlib import Path

# Project root
project_root = Path(__file__).parent.parent


def main():
    """Generate TypeScript interfaces from Python dataclasses."""

    # Ensure output directory exists
    output_dir = project_root / "frontend" / "src" / "types"
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "generated.ts"

    # Input file containing Interface classes
    input_file = project_root / "robot" / "geometry" / "types.py"

    print("Generating TypeScript interfaces...")

    # Run the python-to-typescript-interfaces CLI
    venv_bin = project_root / ".venv" / "bin" / "python-to-typescript-interfaces"

    result = subprocess.run(
        [
            str(venv_bin),
            str(input_file),
            "-o",
            str(output_file),
            "-e",  # Export interfaces
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(f"Error generating types: {result.stderr}", file=sys.stderr)
        sys.exit(1)

    # Add header to generated file
    with open(output_file, "r") as f:
        content = f.read()

    with open(output_file, "w") as f:
        f.write("// AUTO-GENERATED - DO NOT EDIT\n")
        f.write("// Generated by scripts/generate_types.py\n")
        f.write("// Source: robot/geometry/types.py\n\n")
        f.write(content)

    print(f"✓ Generated TypeScript interfaces -> {output_file}")


if __name__ == "__main__":
    main()
